### ISSUE TITLE
Items barely visible in htop using Solarized Dark

### ISSUE THREAD

**Issue by desbma** [Anthony25/gnome-terminal-colors-solarized#49]
Using the  [htop](https://github.com/hishamhm/htop) software and  Solarized Dark for gnome terminal installed from this repo, some items are barely visible (1 min load average, and totals in the cpu/mem bar graphs):
![htop with Solarized color theme](http://i.imgur.com/Z912XJv.png)

I'm not sure if this is a htop or Solarized bug, si I'm opening an [issue](https://github.com/hishamhm/htop/issues/173) on both projects.

**Comment by Anthony25** [comment]
Hello,
yeah, I know, it's directly related to the theme in fact. You can follow the issue on the solarized repo: https://github.com/altercation/solarized/issues/220#issuecomment-77281185

For htop, I personally use the "Black Night" color, it renders well on solarized and doesn't have the "invisible text" issue.

**Comment by desbma** [comment]
Thanks, I close this to avoid duplicates then.

**Comment by Anthony25** [comment]
Ok, thanks for the report !
