### ISSUE TITLE
Broken on Ubuntu 15.04?

### ISSUE THREAD

**Issue by metasoarous** [Anthony25/gnome-terminal-colors-solarized#52]
I just upgraded, and now the solarize command doesn't seem to work. Any thoughts?

**Comment by Anthony25** [comment]
Hello,
I tested in a virtual machine, it seems OK. Are you in this case #47 ?

**Comment by metasoarous** [comment]
Ah; I am using Gnome terminal 3.14.2, so that's possible.

**Comment by Anthony25** [comment]
Ok, so I'm closing it as it's a duplicate. I will find a fix this week end.

**Comment by metasoarous** [comment]
Awesome; cheers.

**Comment by Anthony25** [comment]
In fact, I reopen the issue, as the script still works on Ubuntu 15.04 (just the scripts set_dark.sh and set_light.sh doesn't apply the theme directly for the default profile).

Which error do you get ?

**Comment by Anthony25** [comment]
So ?

**Comment by SPxiaomin** [comment]
the bold blue color show like *a light gray*, what's the reason?

**Comment by Anthony25** [comment]
@SPxiaomin: you should ask that directly on the solarized project, that decides about the color scheme I use.

Repository: https://github.com/altercation/solarized

**Comment by SPxiaomin** [comment]
@Anthony25 thanks

**Comment by Anthony25** [comment]
I'm closing this issue as it didn't get any comment since a few months. Just ask me to reopen it if you want to.
