### ISSUE TITLE
Some folder colors are wrong

### ISSUE THREAD

**Issue by miguelcarax** [Anthony25/gnome-terminal-colors-solarized#54]
With some folder i have the next problem:

![captura de pantalla de 2015-10-01 00-02-29](https://cloud.githubusercontent.com/assets/9194709/10207926/d1ccecba-67cf-11e5-9687-f03fd020716a.png)

gnome-shell, zsh, archlinux

**Comment by Anthony25** [comment]
Hello,
Hum normally the folders with fg:blue and bg:green are the ones with a 777 permission. Folders with an unchanged bg but fg:blue are just "normal folders". I don't see any error here, so could you explain what is the problem please ?

**Comment by miguelcarax** [comment]
Didn't know that, change permission and it's fixed. Thx for information!

**Comment by Anthony25** [comment]
No problem !
