### ISSUE TITLE
Guake comatibility (f12 terminal access)

### ISSUE THREAD

**Issue by arjamizo** [Anthony25/gnome-terminal-colors-solarized#55]
I am using `guake` for `f12` terminal access and you can easily install this theme just by executing 

    curl https://raw.githubusercontent.com/varemenos/guake-color-palettes/master/palettes/guake-solarized-light.sh | bash

**Comment by Anthony25** [comment]
Hello,
Hum yes, but it would not work here. gnome-terminal uses dconf since 3.8 (so I maintain gconf and dconf for the compatibility), and I do a bit more things in my scripts, otherwise they would be obviously shorter :)
