### ISSUE TITLE
Is vim working for others running Debian Stretch, gnome-terminal 3.20.2?

### ISSUE THREAD

**Issue by gkop** [Anthony25/gnome-terminal-colors-solarized#58]
Thanks for this great work! I have been using it happily for years with Debian Wheezy and Jessie.

Unfortunately I am struggling to get the colors right on Stretch after a couple hours of debugging.

```
➜  ~ echo $TERM        
xterm-256color
➜  ~ tput colors       
256
➜  ~ tail -n 1 ~/.vimrc
set t_Co=16
➜  ~ vim --version
➜  ~ vim "+runtime syntax/colortest.vim"
```

vim version returns http://pastie.org/10870984

colortest screenshot:

![colortest](https://cloud.githubusercontent.com/assets/222582/15946064/eeec499e-2e49-11e6-8213-98ccdb5ee882.png)

Interestingly, if I remove `set t_Co=16` from my .vimrc and execute `TERM=xterm vim "+runtime syntax/colortest.vim"`, my black_on_* colors all show up correctly, but several of my *_on_white colors are wrong:

![colors2](https://cloud.githubusercontent.com/assets/222582/15946438/cb2609c6-2e4b-11e6-88fd-8613eefded68.png)

**Comment by gkop** [comment]
Interestingly, if I remove `set t_Co=16` from my .vimrc and execute `TERM=xterm vim "+runtime syntax/colortest.vim"`, my black_on_* colors all show up correctly, but several of my *_on_white colors are wrong:

![colors2](https://cloud.githubusercontent.com/assets/222582/15946414/ae8f92be-2e4b-11e6-8c41-17f09f8c4dd3.png)

**Comment by Anthony25** [comment]
Hello,
Thanks for the report! Did you try with [vim-colors-solarized](https://github.com/altercation/vim-colors-solarized)?

**Comment by gkop** [comment]
Thanks for the quick reply Anthony!

I have never previously used a vim plugin, only this plugin, and been happy with the colors. What does the plugin add?

I tried the plugin (configuring it for 256 colors) and here are my unfortunate results:

![vimcolors-solarized](https://cloud.githubusercontent.com/assets/222582/15950363/097eb8be-2e63-11e6-924b-3ac4dbc7b969.png)

**Comment by Anthony25** [comment]
Yes, I have exactly the same result on urxvt and gnome-terminal.

Actually, I don't really get why, because for example when I pass in insert mode, the yellow color in my vim airline respects the colorscheme, and when I edit some code it's coherent with the screenshots of the vim-color-solarized (the colorscheme doesn't seem to be "broken").

If you get an issue with the palette, maybe you should report it to the official solarized repository, but be aware that the project seems to be dead…

**Comment by gkop** [comment]
The last screenshot is correct? green yellow and blue map to gray?

**Comment by Anthony25** [comment]
By the way, if you want a dark blue bg, set solarized to 16 colours instead of 256.

**Comment by Anthony25** [comment]
And I can't really give you an accurate answer: for me, the vim plugin just adapts the palette to fit with solarized, and specifies some "scenarios" (highlight, etc…). The palette as returned by colortest (and as shown on your screenshot) is not correct, yellow green and blue don't fit, but you'll see when editing some code that you'll have exactly the same colours than those shown in the screenshots at the end of [this page](http://ethanschoonover.com/solarized).

I didn't work on the palette, actually, which is the @altercation job, so if you have any issue with it you really should report that to their repo. I know how to fix some common bugs with solarized, but I will not be able to explain exactly the reason why it fixes them (my job here is only to facilitate the import in gnome-terminal).

**Comment by gkop** [comment]
Thanks Anthony. I guess I was just expecting unofficial solarized results - those that I get on OSX iTerm2 with @altercation's palette and gnome-terminal on Jessie and Wheezy with this palette and vim with no additional color configuration. If I figure out how to get those results on Stretch I will post here - I suspect I'm not the only one that has grown accustomed to these vim colors.

**Comment by gkop** [comment]
This is somewhat embarrassing, but I think I just tracked this issue down to vim switching from `background=light` by default to `background=dark` by default.

**Comment by Anthony25** [comment]
No problem ;)
Cool that you solved your issue, and yes, I am using background=dark too.
