### ISSUE TITLE
cannot install on ubuntu 16.04 

### ISSUE THREAD

**Issue by MarkWh1te** [Anthony25/gnome-terminal-colors-solarized#60]
mark@redqueen:~/personal/gnome-terminal-colors-solarized$ sh install.sh 
install.sh: 4: install.sh: declare: not found
install.sh: 5: install.sh: Syntax error: "(" unexpected

**Comment by Anthony25** [comment]
Hello,
Thanks for your bugreport. Your error is "normal", because you need to use bash, and not sh ;)

**Comment by MarkWh1te** [comment]
yes you are right!  I have fixed this problem by myself! Great work man !

**Comment by Anthony25** [comment]
You're welcome!
