### ISSUE TITLE
CentOS7

### ISSUE THREAD

**Issue by marzzz21** [Anthony25/gnome-terminal-colors-solarized#62]
Tried this one in CentOS7 and it worked like a charm. Just one thing though, it creates a ~/.dir_colors directory containing the dircolors file. This seems not to be the way it should be done on CentOS 7 though as the terminal would display a warning, "~/.dir_colors is a directory". Tried moving the dircolors file to ~/.dir_colors (with the previous ~/.dir_colors directory deleted), and is now enjoying the solarized theme. 

Thank You,
Marz

**Comment by Anthony25** [comment]
Hello,
Thanks for your bugreport! Hum, it is weird, as Ubuntu works with a `dir_colors` directory. Maybe I should look if `~/dir_colors` is already here and is a file, and in this case copy the dircolors as `~/dir_colors`.

I do not think I will have the time this week end to add it, so it will be more probably for next week.

**Comment by Anthony25** [comment]
Hello,
Sorry, I took a very long time to fix this issue.

It should be ok now with CentOS (and every distribution using `~/.dir_colors` as default) when a dircolors already exists, as it will be backup and replace it. Otherwise, if `~/.dir_colors` does not exist, it will. like before, install the new dircolors as `~/dir_colors/dircolors`, and you have to setup your shell to use it.

This way, it avoids me to write a list of exceptions with every distribution and their default dircolors path to know where I should install the dircolors at runtime.

**Comment by dchatterjee172** [comment]
@Anthony25 
How to completely remove dir colors so that the message won't appear again

**Comment by Anthony25** [comment]
Configure your shell to use `~/dir_colors`:

```
if [ -f ~/.dircolors ]
    then eval `dircolors ~/.dircolors`
fi
```

**Comment by Anthony25** [comment]
Or I haven't understood your question

**Comment by Anthony25** [comment]
Just remove the dircolors file `~/.dir_colors/dircolors` or `~/.dir_colors`

**Comment by Abdelkader-gnichi** [comment]
i feel like i'am the holy stupid one in the world please i use fedora 35 and i have the same issue and i don't figure out how to solve it 
terminal out put : 
/usr/bin/cat: /home/gadour/.dir_colors: Is a directory
[gadour@localhost ~]$ 

what i have in the .bashrc:
eval `dircolors ~/.dir_colors/dircolors`

**Comment by Abdelkader-gnichi** [comment]
> i feel like i'am the holy stupid one in the world please i use fedora 35 and i have the same issue and i don't figure out how to solve it terminal out put : /usr/bin/cat: /home/gadour/.dir_colors: Is a directory [gadour@localhost ~]$
> 
> what i have in the .bashrc: eval `dircolors ~/.dir_colors/dircolors`

ok i get it but one thing how can i use the file because all the content is commented with # so how can i use it

**Comment by aruhier** [comment]
Did you install the solarized dircolors?
