### ISSUE TITLE
Profile not found on gnome-terminal 3.22.1

### ISSUE THREAD

**Issue by joshuap** [Anthony25/gnome-terminal-colors-solarized#63]
I am not sure if this is related to #47. I get the following output when installing on a fresh install of Arch w/ Gnome 3/gnome-terminal 3.22.1. Any ideas? Thanks!

```
code/Anthony25/gnome-terminal-colors-solarized ‹master› » ./install.sh

This script will ask you which color scheme you want, and which Gnome Terminal profile to overwrite.

Please note that there is no uninstall option yet. If you do not wish to overwrite any of your profiles, you should create a new profile before you run this script. However, you can reset your colors to the Gnome default, by running:

    Gnome >= 3.8 dconf reset -f /org/gnome/terminal/legacy/profiles:/
    Gnome < 3.8 gconftool-2 --recursive-unset /apps/gnome-terminal

By default, it runs in the interactive mode, but it also can be run non-interactively, just feed it with the necessary options, see 'install.sh --help' for details.

Please select a color scheme:
1) dark
2) dark_alternative
3) light
#? 1

Please select a Gnome Terminal profile:

You have selected:

  Scheme:  dark
Failed to get value for `/apps/gnome-terminal/profiles//visible_name': Bad key or directory name: "/apps/gnome-terminal/profiles//visible_name": Can't have two slashes '/' in a row
  Profile: (No name) ()

Are you sure you want to overwrite the selected profile?
(YES to continue) 
```

**Comment by Anthony25** [comment]
Hello,
Hum, I will take a look at this on a fresh vm, on Arch. It seems to be related to #47, but it is weird because here, half of the files are created, whereas on #47, I had no error, just the default profile that was not detected.

**Comment by Anthony25** [comment]
`gnome-terminal --version` output changed since Gnome 3.22, so the script used an old method to apply the colorscheme (method valid only for Gnome 3.8 or less).

It should be fixed now, but please tell me if you see any error when using it!

**Comment by ZaidaEMtzMo** [comment]
Hi,
I am having the exact same problem. I am using Ubuntu 18.04 and GNOME Terminal 3.28.2
I created different new profiles in my terminal but the script doesn't detect them.
How can I fix this?
Thank you!
![image](https://user-images.githubusercontent.com/33673432/48146394-df9c7a00-e282-11e8-92c9-5a21870a1a36.png)
