### ISSUE TITLE
Install.sh not running

### ISSUE THREAD

**Issue by tokelove** [Anthony25/gnome-terminal-colors-solarized#65]
I'm running the install.sh, but it returns:

install.sh: 4: install.sh: declare: not found
install.sh: 5: install.sh: Syntax error: "(" unexpected

Any ideas?

**Comment by Anthony25** [comment]
Hello,
Just to be sure: are you using bash and not sh to run `install.sh`?

**Comment by tokelove** [comment]
It was my mistake, ran it with sh.
