### ISSUE TITLE
Help Fedora 25

### ISSUE THREAD

**Issue by argentum47** [Anthony25/gnome-terminal-colors-solarized#67]
I chose to install dir colors by chance n install.sh and now every time I run  new terminal it pops up:
`/usr/bin/cat: /home/myhome/.dir_colors: Is a directory` . how do I stop this?

**Comment by Anthony25** [comment]
Hello,
You are running on CentOS, right?

**Comment by argentum47** [comment]
Fedora 25, but I guess you could say CentOS, red hat umbrella I guess

**Comment by Anthony25** [comment]
Ok, it's linked to #62, a thing I have to fix but did not.
You can move `~/.dir_colors/dircolors` as `~/.dir_colors`, because your shell might try to use `~/.dir_colors`.

**Comment by argentum47** [comment]
ah .ok thanks. will close this issue

**Comment by Anthony25** [comment]
You're welcome!

**Comment by Anthony25** [comment]
This is fixed now, see #65

**Comment by JiveyGuy** [comment]
> Ok, it's linked to #62, a thing I have to fix but did not. You can move `~/.dir_colors/dircolors` as `~/.dir_colors`, because your shell might try to use `~/.dir_colors`.

Worked for me after following install instructions for gnome-terminal dracula theme on fedora. Thank you.
