### ISSUE TITLE
how do i change colors for Directories with permissions drwxrwsrwx 

### ISSUE THREAD

**Issue by eg020571** [Anthony25/gnome-terminal-colors-solarized#70]
![image](https://user-images.githubusercontent.com/31349364/29815044-efb40b04-8ccc-11e7-8ba3-357fc2fdfae6.png)

I am unable to read directories names which have drwxrwsrwx permissions with green background ,Can someone suggest some alternative .
i am using solarized dark theme in terminal.

**Comment by Anthony25** [comment]
Hi,
Did you try to install a solarized dircolor: https://github.com/seebi/dircolors-solarized ?

**Comment by eg020571** [comment]
I used it now , thanks @Anthony25  for the help.

Now its working fine.

**Comment by Anthony25** [comment]
Cool, thanks for the issue anyway
