### ISSUE TITLE
Uninstall? deprecated readme - And problem installing

### ISSUE THREAD

**Issue by BarbzYHOOL** [Anthony25/gnome-terminal-colors-solarized#77]
The uninstall instructions for gnome 3.6 are not working

> Gnome 3.6 or lower
> 
> $ rm -r ~/.gconf/apps/gnome-terminal/profiles/Solarized/
> $ gconftool-2 --recursive-unset /apps/gnome-terminal
> 

There is no "/apps/gnome-terminal" and the profile name is more like Profile0 with an xml inside

**Comment by Anthony25** [comment]
Hi,
Thanks a lot for the issue. I am really thinking of cleaning this part of code to maintain Gnome versions that use gconf, as gnome 3.6 was released nearly 6 years ago.

I am curious, what distribution are you using?

**Comment by BarbzYHOOL** [comment]
A derivative from ubuntu 14.04

**Comment by BarbzYHOOL** [comment]
I think it was related to this file .config/fish/fishd.94de80cc1a78

**Comment by Anthony25** [comment]
I don't get it. What is this file?

**Comment by BarbzYHOOL** [comment]
Lol, sorry but I'm trying to reinstall and I think it's not working as intended.

Since I installed it the first time with dark theme, it became completely blue, but not exactly like solarized I guess. Then I uninstalled it, and somehow it became perfect (dunno how), then I logged back and it was again dumb blue.

Now I reinstalled and chose the dark alternative theme and accepted the dir-color, but it didn't change one bit, it's still that deep blue.

I reinstall with the light theme and it's almost the same thing (only some dir colors changed after the eval command).

I'm 90% convinced there is a twist that I'm missing

**Comment by BarbzYHOOL** [comment]
Hmm, sorry to ask again, but any idea on how I can debug this?

I suppose it's not installing in the right path (because I can't switch themes, there is no difference between dark, dark2 and light)

**Comment by Anthony25** [comment]
It should be fixed, sorry for the bug.

**Comment by BarbzYHOOL** [comment]
Wow thanks, how did you know it fixed it completely without me testing ? :P 
By the way my old color was good too, now I don't know if I should go back to the bugged version (no idea how) or stick to the new dark theme (dark alternative is not readable for my case)

xD thank you anyway

**Comment by Anthony25** [comment]
I tested on ubuntu 14.04 on my side, and the path was wrong under gconf.

FYI, I think I will maintain this part of the code for a year, and when Ubuntu 14.04 support will be over, clean the support of Gnome term < 3.8.

**Comment by BarbzYHOOL** [comment]
Normal, I will probably update as well at that moment.

But it's already working very well, I don't expect updates :P that's life changing
