### ISSUE TITLE
How to fully uninstall

### ISSUE THREAD

**Issue by ghost** [Anthony25/gnome-terminal-colors-solarized#81]
https://user-images.githubusercontent.com/72372599/125682408-09c5da83-abc4-400b-a0b9-c15b4a14588f.png
After following uninstall instructions this still appears every time I open a new zsh session.

**Comment by aruhier** [comment]
I think you missed this step:

> The installation script will ask if a solarized dircolors is wanted. It will be downloaded and installed as ~/.dir_colors/dircolors. On CentOS, it can be an issue (see issue #62), as the default setup use ~/.dir_colors as dircolors. In that case, **you should manually move ~/.dir_colors as ~/.dir_colors/dircolors before starting the installation script**.

**Comment by aruhier** [comment]
And to uninstall properly, you can move your old dircolors to `~/.dir_colors`, or simply delete `~/.dir_colors`.
