### ISSUE TITLE
Move or delete downloaded dircolors file

### ISSUE THREAD

**Issue by janpieper** [Anthony25/gnome-terminal-colors-solarized#83]
After running `./install.sh -p <id> -s dark --install-dircolors` I have `~/.dir_colors/dircolors` **and** `$PWD/dircolors` although I only need the one in `~/.dir_colors/dircolors`.

That's because the downloaded file will gets copied to the target directory:

https://github.com/aruhier/gnome-terminal-colors-solarized/blob/9651c41df0f89e87feee0c798779abba0f9395e0/src/dircolors.sh#L41

I don't need the `$PWD/dircolors` file, so I need to delete it manually. Would it be possible to move (`mv` instead of `cp`) the file instead? Or delete it after copying?

If there is any reason for copying instead of moving: What about adding a new flag to move/delete the downloaded file? :thinking:

**Comment by aruhier** [comment]
Hi,
It is on purpose, I don't want to move a file that is tracked by the repository. But you can remove safely the cloned repository after you installed the theme, it is not needed anymore.
